version: '3.7'
services:
  app:
    build: .
    environment:
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: shorten
      MYSQL_PORT: 3306
      MYSQL_HOST: db_mysql2
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    container_name: db_mysql2
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db-data/:/var/lib/mysql
      - "./database/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
volumes:
  db-data:

